spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
    open-in-view: false
  data:
    mongodb:
      host: localhost
      port: 27077
      database: resume
      username: admin
